GET http://192.168.68.106:8080/clinical

###

POST http://192.168.68.106:8080/clinical
Content-Type: application/json

{
    "uuid": "",
    "name": "Dra. Metztli",
    "last_name": "Calva",
    "is_company": false,
    "specialty": "Psiquiatra",
    "email": "metztli_mylove@myheart.com",
    "deleted": false,
    "fb": "https://www.facebook.com/metztli.gonzalezmarquez",
    "instagram": "https://www.instagram.com/drametzpsiquia/",
    "linked_in": "https://mx.linkedin.com/in/metztli-calva-gonzalez-173576159",
    "tik_tok": "https://www.tiktok.com/@metztlicat",
    "twitter": "https://twitter.com/metztli",
    "first_contact_date": "2024-04-05",
    "sales_funnel": "PROSPECT",
    "notes": "Contactada",
    "services_offered": ["WEBSERVICES"],
    "resolution": "Cool Contract",
    "created_by": "882af177f2ad49d1b0ebf88b2c62274a",
  "modified_by": "882af177f2ad49d1b0ebf88b2c62274a"
}

###

GET http://192.168.68.106:8080/clinical/98ef8fef3d584fd2b4aad5052b26cc57

###

PATCH  http://192.168.68.106:8080/clinical
Content-Type: application/json

{
    "uuid": "98ef8fef3d584fd2b4aad5052b26cc57",
    "name": "Dra. Marisela",
    "last_name": "Bezier",
    "is_company": false,
    "specialty": "Pediatra",
    "email": "metztli_mylove@myheart.com",
    "deleted": false,
    "fb": "https://www.facebook.com/metztli.gonzalezmarquez",
    "instagram": "https://www.instagram.com/drametzpsiquia/",
    "linked_in": "https://mx.linkedin.com/in/metztli-calva-gonzalez-173576159",
    "tik_tok": "https://www.tiktok.com/@metztlicat",
    "twitter": null,
    "first_contact_date": "2024-04-05",
    "sales_funnel": "PROSPECT",
    "notes": "Contactada",
    "services_offered": ["WEBSERVICES", "BRANDING"],
    "resolution": "Cool Contract",
    "created_by": "882af177f2ad49d1b0ebf88b2c62274a",
    "modified_by": "03a2b8c588ec40fcbe0925d2658b0be4"
}

###

GET http://192.168.68.106:8080/users

###

POST http://192.168.68.106:8080/users
Content-Type: application/json

{
    "name": "Pilar",
    "last_name": "Cravioto",
    "email": "pilar.cravioto@yayleads.mx",
    "role": "ADMIN",
    "password": "Im_sure_municipal_meeting_train"
}

###

GET http://192.168.68.106:8080/users/671cae6fb18a4a0d98da79808fd6be7e

###

PATCH http://192.168.68.106:8080/users
Content-Type: application/json

{
  "uuid": "671cae6fb18a4a0d98da79808fd6be7e",
  "name": "Pilar",
  "last_name": "Cravioto",
  "email": "pilar.cravioto@yayleads.mx",
  "password": null,
  "role": "ADMIN",
  "notes": "unas notas chidas",
  "deleted": false
}

###

GET http://192.168.68.106:8080/enterprise

###

POST http://192.168.68.106:8080/enterprise
Content-Type: application/json

{
  "uuid": "",
  "name": "Stephanie",
  "last_name": "Best",
  "is_company": true,
  "company_name": "Best Enterprise",
  "line_of_business": "YouTube and Media",
  "email": "stephanie@best.com",
  "phone": "5578442211",
  "deleted": false,
  "fb": "https://facebook.com/bestenterprise",
  "instagram": "https://instagram.com/bestenterprise",
  "linked_in": "@BestEnterprise",
  "tik_tok": "@BestEnterprise",
  "twitter": "@BestEnterprise",
  "first_contact_date": "2023-12-15T15:03:14.000Z",
  "sales_funnel": "NEGOTIATION",
  "notes": "Contacted through facebook",
  "services_offered": [
    "ATTRACTIONOFNEWCLIENTS", "SALESMANAGEMENT"
  ],
  "resolution": "Work in Progress",
  "created_by": "03a2b8c588ec40fcbe0925d2658b0be4",
  "modified_by": "03a2b8c588ec40fcbe0925d2658b0be4"
}

###

GET http://192.168.68.106:8080/enterprise/365f81824afd4b63b6baadbe967c1aa2

###

PATCH http://192.168.68.106:8080/enterprise
Content-Type: application/json

{
  "uuid": "c46042988d6f464f854bb726b9b21e65",
  "name": "Stephanie",
  "last_name": "Best",
  "is_company": true,
  "company_name": "Best Enterprise",
  "line_of_business": "YouTube and Media",
  "email": "stephanie@best.com",
  "phone": "5578442211",
  "deleted": false,
  "fb": "https://facebook.com/bestenterprise",
  "instagram": "https://instagram.com/bestenterprise",
  "linked_in": "@BestEnterprise",
  "tik_tok": "@BestEnterprise",
  "twitter": "@BestEnterprise",
  "first_contact_date": "2023-12-15T15:03:14.000Z",
  "sales_funnel": "NEGOTIATION",
  "notes": "Contacted through facebook",
  "services_offered": [
    "ATTRACTIONOFNEWCLIENTS", "SALESMANAGEMENT"
  ],
  "resolution": "Work in Progress",
  "created_by": "03a2b8c588ec40fcbe0925d2658b0be4",
  "modified_by": "03a2b8c588ec40fcbe0925d2658b0be4"
}

###

POST http://192.168.68.106:8080/enterprise_table
Content-Type: application/json

###

POST http://192.168.68.106:8080/user_htmx/715d406f42d6454e9d4f72c6847da172
Content-Type: text/html

###

POST http://192.168.68.106:8080/user_htmx
Content-Type: text/html

###

GET http://192.168.68.106:8080/help_enterprise_servicios

